name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    name: Deploy
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: gha-utilities/jekyll-build@v0.0.4
        with:
          source: ./
          destination: ./public
      - name: Publish
        uses: cloudflare/wrangler-action@1.1.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
      - name: OhDear
        env:
          OHDEAR_API_TOKEN: ${{ secrets.OHDEAR_API_TOKEN }}
        run: |
          sleep 10 # let Cloudflare become globally consistent
          curl -X POST "https://ohdear.app/api/checks/130744/request-run" -H "Authorization: Bearer $OHDEAR_API_TOKEN" -H "Accept: application/json" -H "Content-Type: application/json"
